# Generated by Django 2.2.7 on 2020-07-27 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Warga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=30)),
                ('tempatlahir', models.CharField(max_length=30)),
                ('tgllahir', models.DateField()),
                ('noktp', models.CharField(max_length=30)),
                ('nokk', models.CharField(max_length=30)),
                ('ktp', models.ImageField(blank=True, upload_to='ktp/')),
                ('statustinggal', models.CharField(choices=[('TE', 'TETAP'), ('KO', 'KONTRAK'), ('KS', 'KOS'), ('PE', 'PEMILIK RUMAH non WARGA')], max_length=30)),
                ('no_rumah', models.CharField(choices=[('1', 'NO 1'), ('2', 'NO 2'), ('3', 'NO 3'), ('23', 'NO 23')], max_length=5)),
            ],
        ),
    ]
